@URL_BASE=http://localhost:8001/api/v1
@ContentType=application/json
###
# @name index
GET {{URL_BASE}}/index
###
# @name pre_register
POST {{URL_BASE}}/user/pre-register
Content-Type: {{ContentType}}
{
  "name": "",
  "email": "",
  "date_of_birth": "",
  "phone_number": "",
  "password": ""
}
###
# @name pre_register
POST {{URL_BASE}}/user/register
Content-Type: {{ContentType}}
{
    "email": "",
    "otp": ""
}