server:
  port: "8001"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "auth_dev"

smtp:
  host: "localhost"
  port: "1025"
  username: ""
  password: ""

jwt:
  secret: "your_secret_key"
